[foramtter.actionlint]
command = "actionlint"
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]

[foramtter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.pinact]
command = "pinact"
options = ["run", "--verify"]
includes = [
  ".github/workflows/*.yml",
  ".github/workflows/*.yaml",
  "**/action.yml",
  "**/action.yaml",
]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh"]

[formatter.tombi]
command = "tombi"
options = ["format"]
includes = ["*.toml"]
